version: '2'
services:
    brock-app:
        image: brock
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://brock-mysql:3306/brock?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    brock-mysql:
        extends:
            file: mysql.yml
            service: brock-mysql
